name: C CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make the project
      run: |
        sudo apt update
        sudo apt-get install libsdl2-dev 
        sudo apt-get install libsdl2-image-dev
        sudo apt-get install build-essential gnome-devel
        sudo apt-get install libgtk-3-dev
        make
    - name: indent the project
      run: |
        sudo apt-get update -y 
        sudo apt-get install -y indent 
        git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | 
        indent -i4 -bad -bap -bbb -bli0 -cdb -sc -cli4 -cbi0 -npcs -nbc -bls -blf -lp -ts4 -nip -pmt -npsl -fca -fc1 -ncs -l79 -lc79 
